<div class="hero-unit">
    
    <h3>Política de Privacidade</h3>

<p>
    A equipe da Avaliação Externa tem um compromisso com o respeito à sua privacidade. Nós reconhecemos que ao optar por responder o questionário, você confia que nós agiremos de maneira responsável em relação a esses dados. Este é o motivo pelo qual nós temos uma política de privacidade para proteger suas informações.
</p>

<h4>Como a Equipe da Avaliação Externa protege o seus dados?</h4>

<p>
Além dos procedimentos padrões de segurança da informação como utilização de senhas em nosso servidor e banco de dados, recursos de criptografias, Firewall, antivírus e protocolos de comunicação com acesso restrito, a base de dados dos questionários não armazenam os dados pessoais dos respondentes, garantindo ainda mais a "NÃO IDENTIFICAÇÃO" dos envolvidos. Dessa forma, mesmo havendo uma invasão no site (provedor de acesso), ainda assim, será muito difícil relacionar alguma informação pessoal dos respondentes ao questionário, visto que as demais informações não estão armazenadas em nosso servidor. Para o procedimento de análise, os questionários serão transferidos do site e submetidos a ferramentas e processos de consolidação. Os relatórios finais apresentarão somente informações agregadas.
</p>

</div>