<div class="jumbotron">

    <h3>Sistema de Gestão da pesquisa do Monitoramento da Rede de Atendimento do Programa Seguro Desemprego</h3>

    <br/>
    <center><img src="/images/logo.png"/></center>
    <br/>

    <h4>Código do SINE:</h4>

    <input type="text" name="codigo_sine" id="codigo_sine"/>

    <a class="btn btn-primary" id="confirmaCodigoSine">Localizar Questionários</a>
    <a class="btn btn-primary" style="display:none;" id="novoQuestionario">Cadastrar Questionário</a>

    <div style="display:none;" class="alert alert-success" id="alertaSucesso"></div>
    <div style="display:none;" class="alert alert-error" id="alertaErro"></div>

    <form id="formSine" method="post" action="/questionario-sine/sine" name="formSine">
        <input type="hidden" name="id_questionario_sine" id="id_questionario_sine"/>
    </form>
    
    <div id="gridContainer1"></div>    

</div>