    <div class="hero-unit">
    <h4>Sistema de Monitoramento e Avaliação (SMA) da Rede de Atendimento do Programa Seguro Desemprego (PSD) - GRUPO DE MONITORAMENTO DAS ATIVIDADES DO PSD</h4>
    
    <br/>
    
    <center><img src="/images/logo.png"/></center>
    
    <br/>
        <p>
            Prezados Coordenadores, Assistentes de Pesquisa e Técnicos de Monitoramento,
        <br/><br/>

        A Coordenação Técnica do SMA do PSD na UFC está disponibilizando o ambiente a ser utilizado pelas equipes regionais para a digitação das informações coletadas nas visitas de monitoramento.O sistema é bastante simples. Siga as instruções abaixo:
        <br/><br/>
        1) Selecionar o tipo de instrumento a ser digitado. Obs.: Estamos enviando a disponibilização do QUESTIONÁRIO GRTE.
        <br/><br/>
        2) Orientação geral: digite o código do posto de atendimento (no formato 9999999-9) e siga as instruções.

    </p>
    
    <br/>
    
    <center>
        <p>
            <form name="frmLogin" id="frmLogin">

                E-mail: <input type="text" name="email" id="email"/>

                Senha: <input type="password" name="senha" id="senha"/>

                <a id="btnLogin" class="btn btn-primary btn-large">
                Login
                </a>
            </form>
        </p>
    </center>
    
    </div>