<div class="jumbotron">

    <h3>Sistema de Gestão da pesquisa do Monitoramento da Rede de Atendimento do Programa Seguro Desemprego</h3>

    <br/>
    <center><img src="/images/logo.png"/></center>
    <br/>

    <h4>Código da GRTE:</h4>

    <input type="text" name="codigo_grte" id="codigo_grte"/>

    <a class="btn btn-primary" id="confirmaCodigoGrte">Localizar Questionários</a>
    <a class="btn btn-primary" style="display:none;" id="novoQuestionario">Cadastrar Questionário</a>

    <div style="display:none;" class="alert alert-success" id="alertaSucesso"></div>
    <div style="display:none;" class="alert alert-error" id="alertaErro"></div>

    <form id="formGrte" method="post" action="/questionario-grte/grte" name="formGrte">
        <input type="hidden" name="id_questionario_grte" id="id_questionario_grte"/>
    </form>
    
    <div id="gridContainer1"></div>    

</div>